name: Check Source

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  check-coding-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install cmake-format
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
        run: pip install -U cmakelang

      - name: Apply Formatting Script
        run: ./format-project.sh

      - name: Check if code adheres to guidelines
        run: |
          if [[ $(git diff-index --name-only --exit-code HEAD) ]]; then
              echo "Ok"
          else
              git diff
              exit -1
          fi
