name: macOS

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  repository_dispatch:
    types: [macos-dispatch]
  # Run this workflow every Sunday at 18:30 to refresh caches
  schedule:
    - cron: "30 18 * * 0"
  workflow_dispatch:

env:
  BUILD_TYPE: Debug
  CACHE_TAG: 0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos-test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clear Cache
        if: ${{ github.event_name == 'schedule' }}
        run: |
          curl \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_CACHE }}" \
            https://api.github.com/repos/yozoon/viennals/actions/caches?key=viennals-dependencies-cache-${{ runner.os }}-${{env.BUILD_TYPE}}-${{ hashFiles( './external/upstream/**CMakeLists.txt' ) }}-${{env.CACHE_TAG}} \
          && sleep 10

      - name: Setup Dependency Cache
        uses: actions/cache@v3
        id: cache-dependencies
        with:
          key: viennals-dependencies-cache-${{ runner.os }}-${{env.BUILD_TYPE}}-${{ hashFiles( './external/upstream/**CMakeLists.txt' ) }}-${{env.CACHE_TAG}}
          path: |
            ${{github.workspace}}/dependencies/Source
            ${{github.workspace}}/dependencies/Build
            ${{github.workspace}}/dependencies/Install

      - name: Configure
        run: |
          cmake -B ./build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DOpenMP_C_FLAGS="-Xpreprocessor -fopenmp -I$(brew --prefix libomp)/include" \
            -DOpenMP_CXX_FLAGS="-Xpreprocessor -fopenmp -I$(brew --prefix libomp)/include" \
            -DOpenMP_C_LIB_NAMES="omp" \
            -DOpenMP_CXX_LIB_NAMES="omp" \
            -DOpenMP_omp_LIBRARY="$(brew --prefix libomp)/lib/libomp.a"

      - name: Build Dependencies
        if: ${{ steps.cache-dependencies.outputs.cache-hit != 'true' }}
        run: cmake --build ./build --target buildDependencies

      - name: Enable Testing Target
        run: cmake -B ./build -DVIENNALS_BUILD_TESTS=ON

      - name: Build Tests
        run: cmake --build ./build

      - name: Run Tests
        working-directory: ${{github.workspace}}/build
        # Run all tests that are not labeled as benchmark
        run: ctest -LE '^benchmark$'

      - name: Trigger Action on ViennaPS Repository
        if: ${{ github.event_name != 'schedule' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_VIENNAPS }}
          repository: yozoon/ViennaPS
          event-type: viennals-update-macos
